diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=hamaral-GAIT
user.email=hamaral@uea.edu.br
core.editor="C:\Users\hiram\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/hiram/Documents/Arduino/hardware/espressif/esp32
gui.recentrepo=C:/Users/hiram/Documents/GitHub/Logica-de-Programacao-para-IA-com-Python/Matriz-e-Roteiro
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/hiramaralIA/Logica-de-Programacao-para-IA-com-Python
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.master1.remote=origin
branch.master1.merge=refs/heads/master1
